*CLASS zbp_ts_r_app1tp DEFINITION
*  PUBLIC
*  FINAL
*  CREATE PUBLIC .
*
*  PUBLIC SECTION.
*  PROTECTED SECTION.
*  PRIVATE SECTION.
*ENDCLASS.

CLASS zbp_ts_r_app1tp DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF yts_r_app1tp.
ENDCLASS.


CLASS zbp_ts_r_app1tp IMPLEMENTATION.
ENDCLASS.
